### ISSUE TITLE
闪电贷搬砖套利的合约可用但效率不高

### ISSUE THREAD

**Issue by Confucian-e** [GarenWoo/0301_FlashSwapAndCallOption#1]
哈哈，你是在学习什么课程或训练营吗。
这种只针对 Uni 某个池子进行 flashloan 以及只针对 Uni 进行 2 个 pair 的 swap 其实效率很低，gas消耗也很大。所以理论可行但实际很少这么用。
我毕设就做的闪电贷搬砖套利，其实很简单就做成通用的，主要靠链下对参数的打包。
而且 Balancer 很适合用闪电贷，因为它可以借出很多种 token 以及目前不收手续费。
repo: https://github.com/Confucian-e/darbitrix-contract/blob/main/contracts/Arbitrage.sol
tx: https://app.blocksec.com/explorer/tx/arbitrum/0x28ba72fc3295e8e0e8cf23200c8f683f30e5a583b44f5adf09a9ba843662ff67

**Comment by GarenWoo** [comment]
对，我感觉出来这个效率低。是登链 openspace 的练习，不是实际应用。你仓库不错我学习学习哈哈😁

**Comment by Confucian-e** [comment]
可以，老哥很强，学习效率蛮高的

**Comment by GarenWoo** [comment]
哈哈，那是，看了你的视频开始启蒙，少走不少弯路 😁
